import sys
from formatAllSpeckData import *
from simplifyOldUserInfo import *
from speckNameToHealthId import *
from createDeviceInfoTable import *
from mergeDeviceInfoTable import *
from createHealthInfoTable import *

def main(argv):
    p = "../data/"
    
    # Read all raw Speck data and process them into json files for ESDR
    # The data batches contains old and new naming formats
    fpath_in = [p+"speck/1/raw/", p+"speck/2/raw/"]
    fpath_out_1 = [p+"speck/1/json/", p+"speck/1/"]
    fpath_out_2 = [p+"speck/2/json/", p+"speck/2/"]
    #formatAllSpeckData(fpath_in[0], fpath_out_1)
    #formatAllSpeckData(fpath_in[1], fpath_out_2)

    # [NOTE: info_old.csv is already edited, running this part of code will override the file]
    # [make sure that you do not call this function if really necessary]
    # [because this file needs to be manually corrected after generated by this function]
    # Read the old user information that EHP provides
    # Then simplify the table to Speck number, zipcode, and device given time
    fpath_in = p+"ehp/user.xlsx"
    fpath_out = p+"ehp/info_old.csv"
    #simplifyOldUserInfo(fpath_in, fpath_out)
    
    # Create a table that maps health case ID and Speck name for new data
    fpath_in = p+"speck/2/json/"
    fpath_out = p+"health/speck_name_to_health_id_new.csv"
    #speckNameToHealthId(fpath_in, fpath_out)

    # Build the device information table
    fpath_in_old = [p+"speck/1/json/", p+"ehp/info_old.csv", p+"health/speck_name_to_health_id_old.csv"]
    fpath_in_new = [p+"speck/2/json/", p+"ehp/info_new.csv", p+"health/speck_name_to_health_id_new.csv"]
    fpath_out_old = p+"result/speck_old.csv"
    fpath_out_new = p+"result/speck_new.csv"
    #createDeviceInfoTable(fpath_in_old, fpath_out_old, "old")
    #createDeviceInfoTable(fpath_in_new, fpath_out_new, "new")

    # Merge device tables
    fpath_in = [p+"ehp/index_calculator.csv", p+"ehp/speck_name_to_zipcode.csv"]
    fpath_out = p+"result/speck.csv"
    #mergeDeviceInfoTable(fpath_in, fpath_out)

    # Build the health information table
    fpath_in = p+"health/health.xlsx"
    fpath_out = p+"result/health.csv"
    #createHealthInfoTable(fpath_in, fpath_out)

if __name__ == "__main__":
    main(sys.argv)
